//
//  LoginPresenter.swift
//  Firebird
//
//  Created by Dyan on 30/10/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentSomething(response: Login.Something.Response)
    func presentError(error: Login.Something.ViewError)
}

class LoginPresenter: LoginPresentationLogic
{
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Login.Something.Response) {
        let viewModel = Login.Something.ViewModel(userModel: response.userModel)
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentError(error: Login.Something.ViewError) {
        let viewError = Login.Something.ViewError(error: error)
        viewController?.displayError(error: viewError)
    }
}
