//
//  LoginRouter.swift
//  Firebird
//
//  Created by Dyan on 30/10/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    func routeToHome()
    func routeToRegister()
}

protocol LoginDataPassing
{
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    func routeToHome()
    {
        let destionationVC = HomeViewController()
        navigateToSPush(source: viewController!, destination: destionationVC)
    }
    
    func routeToRegister()
    {
        let destionationVC = RegisterViewController()
        navigateToSPush(source: viewController!, destination: destionationVC)
    }
    
    // MARK: Navigation
    
    func navigateToSPush(source: LoginViewController, destination: UIViewController)
    {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToModal(source: LoginDataStore, destination: UIViewController)
    {
//        destination.modalPresentationStyle = .fullScreen
//        source.showDetailViewController(destination, sender: dataStore)
    }
}
